#!/usr/bin/env python3
"""Validate Apple string catalogs and emit plain .strings for CLT-only builds."""

import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
RESOURCES = ROOT / "Sources/Switchboard/Resources"
LANGUAGES = ("en", "ko")


def swift_name(key: str) -> str:
    words = key.split(".")
    return words[0] + "".join(word[0].upper() + word[1:] for word in words[1:])


def read_catalog(path: Path) -> dict[str, dict[str, str]]:
    catalog = json.loads(path.read_text())
    result = {language: {} for language in LANGUAGES}
    for key, entry in catalog["strings"].items():
        placeholders = None
        for language in LANGUAGES:
            unit = entry["localizations"][language]["stringUnit"]
            value = unit["value"]
            if unit["state"] != "translated" or not value.strip():
                raise ValueError(f"Incomplete translation: {path.name}/{key}/{language}")
            parameters = re.findall(r"%(?:\d+\$)?([@dfisu])", value.replace("%%", ""))
            if placeholders is not None and sorted(parameters) != placeholders:
                raise ValueError(f"Format placeholders differ: {path.name}/{key}")
            placeholders = sorted(parameters)
            result[language][key] = value
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args()
    catalogs = {path.stem: read_catalog(path) for path in sorted(RESOURCES.glob("*.xcstrings"))}
    keys = sorted(catalogs["Localizable"]["en"])
    cases = [swift_name(key) for key in keys]
    if len(set(cases)) != len(cases):
        raise ValueError("Localized Swift key names collide")
    generated = (
        "// SPDX-License-Identifier: AGPL-3.0-only\n"
        "// Generated by scripts/compile-localizations.py. Do not edit.\n\n"
        "enum TextKey: String, CaseIterable, Sendable {\n"
        + "".join(f'    case {swift_name(key)} = "{key}"\n' for key in keys)
        + "}\n"
    )
    target = ROOT / "Sources/Switchboard/TextKey.swift"
    if options.check:
        if not target.exists() or target.read_text() != generated:
            raise ValueError("TextKey.swift is out of date; run scripts/compile-localizations.py")
    else:
        target.write_text(generated)
        for table, languages in catalogs.items():
            for language, entries in languages.items():
                folder = ROOT / "build/Localizations" / f"{language}.lproj"
                folder.mkdir(parents=True, exist_ok=True)
                text = "\n".join(
                    f"{json.dumps(key)} = {json.dumps(value, ensure_ascii=False)};"
                    for key, value in sorted(entries.items())
                )
                (folder / f"{table}.strings").write_text(text + "\n")
    print(f"Localization: {len(keys)} UI keys, English/Korean complete")


if __name__ == "__main__":
    main()
