import SwiftUI

/// Original vector mark, matching the icon generated by the build script.
struct SwitchboardMark: View {
    var body: some View {
        Canvas { context, size in
            let scale = size.width / 64
            let background = Path(roundedRect: CGRect(origin: .zero, size: size), cornerRadius: 14 * scale)
            context.fill(background, with: .color(Color(red: 0.10, green: 0.43, blue: 0.91)))
            for (index, height) in [10.0, 26, 42, 26, 10].enumerated() {
                let bar = CGRect(
                    x: (10 + Double(index) * 10) * scale,
                    y: (32 - height / 2) * scale, width: 4 * scale, height: height * scale)
                context.fill(Path(roundedRect: bar, cornerRadius: 2 * scale), with: .color(.white))
            }
        }
        .aspectRatio(1, contentMode: .fit)
        .accessibilityHidden(true)
    }
}
